language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_905b4735a0a5_key -iv $encrypted_905b4735a0a5_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 666 ~/.ssh/id_rsa
- echo -e "Host 47.92.148.206\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp -r ./dist/ root@47.92.148.206:/home/
script:
- npm build
