language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_905b4735a0a5_key -iv $encrypted_905b4735a0a5_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.92.93.223\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp -r dist.zip root@47.92.93.223:/root/www/
script:
- npm build
- unzip buid.zip
